train: C:\Users\ANSHUL M\Downloads\RDD2022_India\India\train\images
val: C:\Users\ANSHUL M\Downloads\RDD2022_India\India\train\images
test: C:\Users\ANSHUL M\Downloads\RDD2022_India\India\test\images
nc: 4
names: ["D00", "D10", "D20", "D40"]
